### ISSUE TITLE
Tailscale inside pods: How to get reliable direct connections?

### ISSUE THREAD

**Issue by JJGadgets** [JJGadgets/Biohazard#285]
## Goal
Allow Tailscale pods to be exposed for direct connections from other devices to Tailscale pods.
Avoid going through relays, since most connections are either roaming to home or within home (avoid extra hop).
Use Tailscale operator to share apps like Kavita and Jellyfin to other Tailnet users, which doesn't allow setting custom labels on the deployed pods, nor does it have predictable labels.

## Todo
- [ ] Check with others if their Tailscale pods can establish direct connections when roaming to home (other devices to Tailscale)
- [ ] Check why SSDP packets (dest 239.255.255.250 UDP port 1900) are being dropped according to Hubble because `TTL exceeded DROPPED (UDP)` but netpols allow it
- [ ] Check if MTU is the reason for the above (cannot confirm, but 9000 MTU on both router and Kubernetes nodes makes the Hubble CLI not show the TTL exceeded dropped flows but Hubble UI shows it)

## Ideas
- Add Multus as 2nd interface in Tailscale pods to another VLAN where static port forwarding or NAT-PMP/UPnP/PCP is allowed (if Tailscale operator doesn't yet support it and Multus can't target controllers, use Kyverno to add labels to managed pods)
- Tailscale DERP relay on OPNsense (`go install derper`? extension?)
- Tailscale DERP relay on Kubernetes (custom container image, port forward?)
- ???

**Comment by JJGadgets** [comment]
Regular Funnel or non-eBPF CNIs might be happier in terms of ease of routing to Tailscale pods? Either that, or fluke testing because other side of Tailscale pod was reachable as a listener.

**Comment by JJGadgets** [comment]
Closed as not using Tailscale anymore.
